In [ ]:
#Leo Murch
#P2
#09/18/2026

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print('Problem 1')
#use the same on as in hw4,
#np.random.normal(55, 13, N)

Problem 1


array([34.12301795, 49.25751847, 57.20851946, 38.77280679, 22.73208959,
       89.39187898, 55.73855234, 45.17772555, 55.15828301, 75.20136751])

In [ ]:
print('Problem 2')
#do it for 10 times
N = (10,10)
sample = np.random.normal(55, 13, N) #make a 10x10 for the full sample

"""
data_sample = [] #empty list to put the 10x3
i = 0
for row in sample:
    #append mean, std, and the row number
    mu = np.mean(row)
    sigma = np.std(row)
    data_sample.append([i, mu, sigma])
    i+=1 #index for row (probably could do with for i in blah blah but
    #row in sample is easier for writing the mean and std)
print(data_sample)
"""
#ill try w/out for loop
sample_num = np.transpose(np.arange(10))
means = np.transpose(np.mean(sample, axis = 0))
stdevs = np.transpose(np.std(sample, axis = 0))
data_sample = np.column_stack((sample_num, means, stdevs))

#stole column_stack from ai, didnt know of it (but now i do!)
print(data_sample)


Problem 2
[[ 0.         58.19408107 10.50224134]
 [ 1.         56.41223311  7.82328904]
 [ 2.         58.67962575 12.48777215]
 [ 3.         54.11201459  7.91522851]
 [ 4.         61.01859097  9.39792358]
 [ 5.         50.12745536 10.56219125]
 [ 6.         58.31837775 11.15144429]
 [ 7.         62.01497056 13.28537887]
 [ 8.         48.8495229  20.72235139]
 [ 9.         55.40801286 12.15954889]]


In [88]:
print('Problem 3')
#prompt:
#for problem 3, ignore my attempts and do this using np.random.normal()
#and then a picture of problem 1 and 2

#ai code:
mu = 55
sigma = 13
N = 10
n_samples = 10
# 10 independent samples, 10 draws each
draws = np.random.normal(mu, sigma, size=(n_samples, N))
data_sample = np.column_stack((
    np.arange(n_samples),          # sample number 0–9
    np.mean(draws, axis=1),        # mean of each sample
    np.std(draws, axis=1),         # std of each sample
))
print(data_sample)

Problem 3
[[ 0.         57.62836666 13.74232075]
 [ 1.         56.51538261 11.80742535]
 [ 2.         51.90158552 15.8114901 ]
 [ 3.         57.17140343 17.44409075]
 [ 4.         56.85888482  9.04102996]
 [ 5.         57.73456386 11.87309703]
 [ 6.         44.16189668 14.95546225]
 [ 7.         52.63864375 15.53786243]
 [ 8.         58.86162599 11.01952935]
 [ 9.         59.05045831  9.31853658]]
