In [ ]:
#Leo Murch
#HW3
#09/16/2026

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os

In [20]:
print("Problem 2")

#import by beautifully complex function
from hw3_aleonav_support_functions import square

#part h;
test_square_1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(square(test_square_1))

#part i;
test_square_2 = np.linspace(0.0, 25.0, 25).reshape(5,5) #need 25 even spaces between for 26 elements
print(square(test_square_2))

Problem 2
[ 0  1  4  9 16 25 36 49 64 81]
[[  0.           1.08506944   4.34027778   9.765625    17.36111111]
 [ 27.12673611  39.0625      53.16840278  69.44444444  87.890625  ]
 [108.50694444 131.29340278 156.25       183.37673611 212.67361111]
 [244.140625   277.77777778 313.58506944 351.5625     391.71006944]
 [434.02777778 478.515625   525.17361111 574.00173611 625.        ]]
